//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class TitlesListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private TitlesListDetail() : base("LightSwitchApplication:TitlesListDetail")
        {
            global::LightSwitchApplication.TitlesListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static TitlesListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.TitlesListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TitlesListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Titles_SelectionChanged();

        partial void Titles_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Titles_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Titles visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Title> Titles
        {
            get
            {
                return global::LightSwitchApplication.TitlesListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties.Titles);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Titles_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the Method screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Method()
        {
            this.Details.Methods.Method.CreateInvocation().Execute();
        }
        partial void Method_CanExecute(ref bool result);
        partial void Method_Execute();

        /// <summary>
        /// Calls the AddToCachedMovies screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void AddToCachedMovies()
        {
            this.Details.Methods.AddToCachedMovies.CreateInvocation().Execute();
        }
        partial void AddToCachedMovies_CanExecute(ref bool result);
        partial void AddToCachedMovies_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties.Titles;
                var initializeCommandEntry = global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties.Method;
                var initializeMethodEntry = global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties.Method;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry
                __TitlesListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeCreated,
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeActivated,
                    global::LightSwitchApplication.TitlesListDetail.DetailsClass.__TitlesListDetail_InvokeSaveErrorEvent);
            private static void __TitlesListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.TitlesListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.TitlesListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __TitlesListDetail_InvokeSavingEvent(global::LightSwitchApplication.TitlesListDetail s)
            {
                bool handled = false;
                s.TitlesListDetail_Saving(ref handled);
                return handled;
            }
            private static void __TitlesListDetail_InvokeSavedEvent(global::LightSwitchApplication.TitlesListDetail s)
            {
                s.TitlesListDetail_Saved();
            }
            private static bool __TitlesListDetail_InvokeClosingEvent(global::LightSwitchApplication.TitlesListDetail s)
            {
                bool cancel = false;
                s.TitlesListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __TitlesListDetail_InvokeCreated(global::LightSwitchApplication.TitlesListDetail s)
            {
                s.TitlesListDetail_Created();
            }
            private static void __TitlesListDetail_InvokeActivated(global::LightSwitchApplication.TitlesListDetail s)
            {
                s.TitlesListDetail_Activated();
            }
            private static bool __TitlesListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.TitlesListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.TitlesListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable TitlesQuery()
            {
                return this.Screen.DataWorkspace.NetflixCatalogData.Titles;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.Title>.Data _Titles;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data _MethodCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data _AddToCachedMoviesCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data _MethodMethod;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data _AddToCachedMoviesMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.Title> Titles
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.Title>)base.GetItem(global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties.Titles);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass> Method
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties.Method);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass> AddToCachedMovies
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties.AddToCachedMovies);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass> Method
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties.Method);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass> AddToCachedMovies
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties.AddToCachedMovies);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.Title>.Entry
                    Titles = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.Title>.Entry(
                        "Titles",
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties._Titles_Stub,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties._Titles_Validate,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties._Titles_CreateQuery,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties._Titles_SelectionChanged,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties._Titles_OnCollectionChanged,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.PropertySetProperties._Titles_OnLoaded);
                private static void _Titles_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::LightSwitchApplication.Title>.Data> c, global::LightSwitchApplication.TitlesListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Titles, sf);
                }
                private static void _Titles_Validate(global::LightSwitchApplication.TitlesListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Titles_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Titles_CreateQuery(global::LightSwitchApplication.TitlesListDetail.DetailsClass d, object[] args)
                {
                    return d.TitlesQuery();
                }
                private static void _Titles_SelectionChanged(global::LightSwitchApplication.TitlesListDetail s)
                {
                    s.Titles_SelectionChanged();
                }
                private static void _Titles_OnCollectionChanged(global::LightSwitchApplication.TitlesListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Titles_Changed(e);
                }
                private static void _Titles_OnLoaded(global::LightSwitchApplication.TitlesListDetail s, bool succeeded)
                {
                    s.Titles_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry
                    Method = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry(
                        "Method",
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties._Method_Stub,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties._Method_CreateExecutableObject);
                private static void _Method_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.TitlesListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Method_CreateExecutableObject(global::LightSwitchApplication.TitlesListDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.TitlesListDetail.DetailsClass)d).Methods.Method.CreateInvocation();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry
                    AddToCachedMovies = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry(
                        "AddToCachedMovies",
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties._AddToCachedMovies_Stub,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.CommandSetProperties._AddToCachedMovies_CreateExecutableObject);
                private static void _AddToCachedMovies_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.TitlesListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._AddToCachedMoviesCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _AddToCachedMovies_CreateExecutableObject(global::LightSwitchApplication.TitlesListDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.TitlesListDetail.DetailsClass)d).Methods.AddToCachedMovies.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry
                    Method = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry(
                        "Method",
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties._Method_Stub,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties._Method_CanInvoke,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties._Method_InvokeMethod);
                private static void _Method_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.TitlesListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodMethod, sf);
                }
                private static global::System.Exception _Method_CanInvoke(global::LightSwitchApplication.TitlesListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Method_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Method_InvokeMethod(global::LightSwitchApplication.TitlesListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Method_Execute();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry
                    AddToCachedMovies = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Entry(
                        "AddToCachedMovies",
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties._AddToCachedMovies_Stub,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties._AddToCachedMovies_CanInvoke,
                        global::LightSwitchApplication.TitlesListDetail.DetailsClass.MethodSetProperties._AddToCachedMovies_InvokeMethod);
                private static void _AddToCachedMovies_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TitlesListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.TitlesListDetail, global::LightSwitchApplication.TitlesListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.TitlesListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._AddToCachedMoviesMethod, sf);
                }
                private static global::System.Exception _AddToCachedMovies_CanInvoke(global::LightSwitchApplication.TitlesListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.AddToCachedMovies_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _AddToCachedMovies_InvokeMethod(global::LightSwitchApplication.TitlesListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.AddToCachedMovies_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class CachedMoviesSetListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CachedMoviesSetListDetail() : base("LightSwitchApplication:CachedMoviesSetListDetail")
        {
            global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CachedMoviesSetListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.CachedMoviesSetListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSetListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void CachedMoviesSet_SelectionChanged();

        partial void CachedMoviesSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the CachedMoviesSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.CachedMovies> CachedMoviesSet
        {
            get
            {
                return global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties.CachedMoviesSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMoviesSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties.CachedMoviesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass>.Entry
                __CachedMoviesSetListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeCreated,
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeActivated,
                    global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.__CachedMoviesSetListDetail_InvokeSaveErrorEvent);
            private static void __CachedMoviesSetListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CachedMoviesSetListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CachedMoviesSetListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CachedMoviesSetListDetail_InvokeSavingEvent(global::LightSwitchApplication.CachedMoviesSetListDetail s)
            {
                bool handled = false;
                s.CachedMoviesSetListDetail_Saving(ref handled);
                return handled;
            }
            private static void __CachedMoviesSetListDetail_InvokeSavedEvent(global::LightSwitchApplication.CachedMoviesSetListDetail s)
            {
                s.CachedMoviesSetListDetail_Saved();
            }
            private static bool __CachedMoviesSetListDetail_InvokeClosingEvent(global::LightSwitchApplication.CachedMoviesSetListDetail s)
            {
                bool cancel = false;
                s.CachedMoviesSetListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __CachedMoviesSetListDetail_InvokeCreated(global::LightSwitchApplication.CachedMoviesSetListDetail s)
            {
                s.CachedMoviesSetListDetail_Created();
            }
            private static void __CachedMoviesSetListDetail_InvokeActivated(global::LightSwitchApplication.CachedMoviesSetListDetail s)
            {
                s.CachedMoviesSetListDetail_Activated();
            }
            private static bool __CachedMoviesSetListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.CachedMoviesSetListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.CachedMoviesSetListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CachedMoviesSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.CachedMoviesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMovies>.Data _CachedMoviesSet;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMovies> CachedMoviesSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMovies>)base.GetItem(global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties.CachedMoviesSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMovies>.Entry
                    CachedMoviesSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMovies>.Entry(
                        "CachedMoviesSet",
                        global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties._CachedMoviesSet_Stub,
                        global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties._CachedMoviesSet_Validate,
                        global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties._CachedMoviesSet_CreateQuery,
                        global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties._CachedMoviesSet_SelectionChanged,
                        global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties._CachedMoviesSet_OnCollectionChanged,
                        global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass.PropertySetProperties._CachedMoviesSet_OnLoaded);
                private static void _CachedMoviesSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CachedMoviesSetListDetail, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass, global::LightSwitchApplication.CachedMovies>.Data> c, global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._CachedMoviesSet, sf);
                }
                private static void _CachedMoviesSet_Validate(global::LightSwitchApplication.CachedMoviesSetListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CachedMoviesSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CachedMoviesSet_CreateQuery(global::LightSwitchApplication.CachedMoviesSetListDetail.DetailsClass d, object[] args)
                {
                    return d.CachedMoviesSetQuery();
                }
                private static void _CachedMoviesSet_SelectionChanged(global::LightSwitchApplication.CachedMoviesSetListDetail s)
                {
                    s.CachedMoviesSet_SelectionChanged();
                }
                private static void _CachedMoviesSet_OnCollectionChanged(global::LightSwitchApplication.CachedMoviesSetListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CachedMoviesSet_Changed(e);
                }
                private static void _CachedMoviesSet_OnLoaded(global::LightSwitchApplication.CachedMoviesSetListDetail s, bool succeeded)
                {
                    s.CachedMoviesSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
