

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class CachedMovies : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the CachedMovies entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CachedMovies()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CachedMovies(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CachedMovies> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CachedMovies.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMovies_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CachedMovies_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.CachedMovies.DetailsClass.GetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.CachedMovies.DetailsClass.SetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.CachedMovies.DetailsClass.GetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.CachedMovies.DetailsClass.SetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.CachedMovies.DetailsClass.GetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.CachedMovies.DetailsClass.SetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Rating
        {
            get
            {
                return global::LightSwitchApplication.CachedMovies.DetailsClass.GetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Rating);
            }
            set
            {
                global::LightSwitchApplication.CachedMovies.DetailsClass.SetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Rating, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rating_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rating_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rating_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ReleaseYear
        {
            get
            {
                return global::LightSwitchApplication.CachedMovies.DetailsClass.GetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.ReleaseYear);
            }
            set
            {
                global::LightSwitchApplication.CachedMovies.DetailsClass.SetValue(this, global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.ReleaseYear, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReleaseYear_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReleaseYear_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReleaseYear_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CachedMovies,
                global::LightSwitchApplication.CachedMovies.DetailsClass,
                global::LightSwitchApplication.CachedMovies.DetailsClass.IImplementation,
                global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass>.Entry
                __CachedMoviesEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass>.Entry(
                    global::LightSwitchApplication.CachedMovies.DetailsClass.__CachedMovies_CreateNew,
                    global::LightSwitchApplication.CachedMovies.DetailsClass.__CachedMovies_Created,
                    global::LightSwitchApplication.CachedMovies.DetailsClass.__CachedMovies_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CachedMovies __CachedMovies_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CachedMovies> es)
            {
                return new global::LightSwitchApplication.CachedMovies(es);
            }
            private static void __CachedMovies_Created(global::LightSwitchApplication.CachedMovies e)
            {
                e.CachedMovies_Created();
            }
            private static bool __CachedMovies_AllowSaveWithErrors(global::LightSwitchApplication.CachedMovies e)
            {
                bool result = false;
                e.CachedMovies_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string> Rating
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.Rating) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int> ReleaseYear
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties.ReleaseYear) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Title { get; set; }
                new string Rating { get; set; }
                new int ReleaseYear { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CachedMovies.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Data> c, global::LightSwitchApplication.CachedMovies.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.CachedMovies e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.CachedMovies e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.CachedMovies e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CachedMovies.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.CachedMovies.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.CachedMovies e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.CachedMovies e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.CachedMovies e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CachedMovies.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Data> c, global::LightSwitchApplication.CachedMovies.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.CachedMovies e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.CachedMovies e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.CachedMovies e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Entry
                    Rating = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Entry(
                        "Rating",
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Rating_Stub,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Rating_ComputeIsReadOnly,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Rating_Validate,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Rating_GetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Rating_SetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._Rating_OnValueChanged);
                private static void _Rating_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CachedMovies.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Data> c, global::LightSwitchApplication.CachedMovies.DetailsClass d, object sf)
                {
                    c(d, ref d._Rating, sf);
                }
                private static bool _Rating_ComputeIsReadOnly(global::LightSwitchApplication.CachedMovies e)
                {
                    bool result = false;
                    e.Rating_IsReadOnly(ref result);
                    return result;
                }
                private static void _Rating_Validate(global::LightSwitchApplication.CachedMovies e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Rating_Validate(r);
                }
                private static string _Rating_GetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d)
                {
                    return d.ImplementationEntity.Rating;
                }
                private static void _Rating_SetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Rating = v;
                }
                private static void _Rating_OnValueChanged(global::LightSwitchApplication.CachedMovies e)
                {
                    e.Rating_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Entry
                    ReleaseYear = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Entry(
                        "ReleaseYear",
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._ReleaseYear_Stub,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._ReleaseYear_ComputeIsReadOnly,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._ReleaseYear_Validate,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._ReleaseYear_GetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._ReleaseYear_SetImplementationValue,
                        global::LightSwitchApplication.CachedMovies.DetailsClass.PropertySetProperties._ReleaseYear_OnValueChanged);
                private static void _ReleaseYear_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CachedMovies.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Data> c, global::LightSwitchApplication.CachedMovies.DetailsClass d, object sf)
                {
                    c(d, ref d._ReleaseYear, sf);
                }
                private static bool _ReleaseYear_ComputeIsReadOnly(global::LightSwitchApplication.CachedMovies e)
                {
                    bool result = false;
                    e.ReleaseYear_IsReadOnly(ref result);
                    return result;
                }
                private static void _ReleaseYear_Validate(global::LightSwitchApplication.CachedMovies e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ReleaseYear_Validate(r);
                }
                private static int _ReleaseYear_GetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d)
                {
                    return d.ImplementationEntity.ReleaseYear;
                }
                private static void _ReleaseYear_SetImplementationValue(global::LightSwitchApplication.CachedMovies.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ReleaseYear = v;
                }
                private static void _ReleaseYear_OnValueChanged(global::LightSwitchApplication.CachedMovies e)
                {
                    e.ReleaseYear_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, string>.Data _Rating;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CachedMovies, global::LightSwitchApplication.CachedMovies.DetailsClass, int>.Data _ReleaseYear;
            
        }
    
        #endregion
    }
    
    #endregion
}
